const db=window.autorentDb;let currentUser=null,currentAgency=null,vehicles=[];
const $=id=>document.getElementById(id);
async function boot(){currentUser=await getAutoRentUser();if(!currentUser){location.href='index.html';return}const profile=await getAutoRentProfile();if(profile?.role!=='loueur'){location.href='client.html';return}await loadAgency();}
async function loadAgency(){const {data}=await db.from('agencies').select('*').eq('owner_id',currentUser.id).maybeSingle();currentAgency=data||null;if(!currentAgency){$('setup').style.display='block';$('dashboard').style.display='none';return}$('setup').style.display='none';$('dashboard').style.display='block';$('agencyName').textContent=currentAgency.name;await Promise.all([loadFleet(),loadBookings()]);}
async function createAgency(){const name=$('agencyInput').value.trim(),city=$('agencyCity').value,email=$('agencyEmail').value.trim(),phone=$('agencyPhone').value.trim();if(!name||!city){$('agencyMsg').textContent='Nom et ville obligatoires.';return}const slug=(name+'-'+Date.now()).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const {error}=await db.from('agencies').insert({owner_id:currentUser.id,name,slug,city,email:email||currentUser.email,phone});if(error){$('agencyMsg').textContent=error.message;return}await loadAgency();}
async function loadFleet(){const {data,error}=await db.from('vehicles').select('*').eq('agency_id',currentAgency.id).order('created_at',{ascending:false});if(error)return;vehicles=data||[];$('vehicleCount').textContent=vehicles.length;$('fleetGrid').innerHTML=vehicles.length?vehicles.map(v=>`<article class="car"><div class="car-top">${v.image_url?`<img src="${v.image_url}" alt="" style="width:100%;height:100%;object-fit:cover">`:'🚗'}</div><div class="car-body"><h3>${v.brand} ${v.model}</h3><div class="meta">${v.city} · ${v.price_per_day} DH/j</div><div class="features"><span>${v.transmission||'—'}</span><span>${v.status}</span><span>Caution ${v.deposit||0} DH</span></div><button class="ghost" onclick="toggleVehicle('${v.id}','${v.status}')">${v.status==='available'?'Rendre indisponible':'Rendre disponible'}</button></div></article>`).join(''):'<p class="meta">Aucun véhicule. Ajoutez votre premier véhicule.</p>';}
function openVehicleForm(){$('vehicleForm').showModal();}
async function addVehicle(){const payload={agency_id:currentAgency.id,brand:$('vBrand').value.trim(),model:$('vModel').value.trim(),year:Number($('vYear').value)||null,city:$('vCity').value,transmission:$('vTransmission').value,fuel_type:$('vFuel').value,seats:Number($('vSeats').value)||5,price_per_day:Number($('vPrice').value),deposit:Number($('vDeposit').value)||0,mileage_policy:$('vKm').value.trim(),insurance_details:$('vInsurance').value.trim(),airport_delivery:$('vAirport').checked,hotel_delivery:$('vHotel').checked,status:'available'};if(!payload.brand||!payload.model||!payload.price_per_day){$('vehicleMsg').textContent='Marque, modèle et prix obligatoires.';return}const {error}=await db.from('vehicles').insert(payload);if(error){$('vehicleMsg').textContent=error.message;return}$('vehicleForm').close();await loadFleet();}
async function toggleVehicle(id,status){await db.from('vehicles').update({status:status==='available'?'unavailable':'available',updated_at:new Date().toISOString()}).eq('id',id);await loadFleet();}
async function loadBookings(){const {data,error}=await db.from('bookings').select('*,vehicles(brand,model,city,price_per_day),profiles(full_name)').eq('agency_id',currentAgency.id).order('created_at',{ascending:false});if(error)return;const list=data||[];$('pendingCount').textContent=list.filter(b=>b.status==='pending').length;$('bookingList').innerHTML=list.length?list.map(b=>`<div class="bubble bot"><b>${b.vehicles?.brand||''} ${b.vehicles?.model||''}</b> — ${b.starts_on} → ${b.ends_on} — ${b.total_price||'—'} DH<br><span class="meta">Statut: ${b.status}</span>${b.client_message?`<br><span class="meta">${b.client_message}</span>`:''}${b.status==='pending'?`<br><br><button class="primary" onclick="setBooking('${b.id}','confirmed')">Confirmer</button> <button class="ghost" onclick="setBooking('${b.id}','rejected')">Refuser</button>`:''}</div>`).join(''):'<p class="meta">Aucune réservation.</p>';}
async function setBooking(id,status){await db.from('bookings').update({status,updated_at:new Date().toISOString()}).eq('id',id);await loadBookings();}
window.createAgency=createAgency;window.openVehicleForm=openVehicleForm;window.addVehicle=addVehicle;window.toggleVehicle=toggleVehicle;window.setBooking=setBooking;boot();