const cars=[{name:'Dacia Logan',city:'Marrakech',price:320,gear:'Manuelle',deposit:'2 000 DH',km:'Illimité',icon:'🚙',sponsored:false},{name:'Renault Clio 5',city:'Casablanca',price:390,gear:'Automatique',deposit:'3 000 DH',km:'200 km/j',icon:'🚗',sponsored:true},{name:'Dacia Duster',city:'Agadir',price:520,gear:'Automatique',deposit:'3 500 DH',km:'Illimité',icon:'🚘',sponsored:false},{name:'Peugeot 208',city:'Rabat',price:410,gear:'Automatique',deposit:'2 500 DH',km:'250 km/j',icon:'🚗',sponsored:false},{name:'Hyundai Tucson',city:'Tanger',price:650,gear:'Automatique',deposit:'4 000 DH',km:'Illimité',icon:'🚙',sponsored:false},{name:'Fiat 500',city:'Fès',price:350,gear:'Manuelle',deposit:'2 000 DH',km:'200 km/j',icon:'🚗',sponsored:false}];
const grid=document.getElementById('carGrid'),modal=document.getElementById('modal'),content=document.getElementById('modalContent');let pendingCar=null;
function render(list=cars){grid.innerHTML=list.map(c=>{const i=cars.indexOf(c);return `<article class="car"><div class="car-top">${c.sponsored?'<span class="badge">Sponsorisé</span>':''}${c.icon}</div><div class="car-body"><h3>${c.name}</h3><div class="meta">📍 ${c.city}</div><div class="features"><span>${c.gear}</span><span>🛡 Assurance</span><span>${c.km}</span><span>Caution ${c.deposit}</span></div><div class="price-row"><div class="price"><b>${c.price} DH</b><small> / jour</small></div><button class="primary" onclick="reserve(${i})">Réserver</button></div></div></article>`}).join('')}
render();
function reserve(i){pendingCar=cars[i];content.innerHTML=`<h2>Demande de réservation</h2><p><b>${pendingCar.name}</b> — ${pendingCar.city} — ${pendingCar.price} DH/jour</p><p>Aucun paiement en ligne. Le loueur devra confirmer ou refuser la demande.</p><label>Nom<input id="bookingName" placeholder="Votre nom"></label><br><label>Email<input id="bookingEmail" type="email" placeholder="vous@email.com"></label><br><br><button class="primary" onclick="confirmation()">Envoyer la demande</button>`;modal.showModal()}
function confirmation(){const name=document.getElementById('bookingName')?.value.trim()||'Client';const email=document.getElementById('bookingEmail')?.value.trim()||'';const bookings=JSON.parse(localStorage.getItem('autorentBookings')||'[]');const ref='REQ-'+String(Date.now()).slice(-6);bookings.unshift({ref,name,email,car:pendingCar.name,city:pendingCar.city,price:pendingCar.price,status:'En attente',createdAt:new Date().toISOString()});localStorage.setItem('autorentBookings',JSON.stringify(bookings));content.innerHTML=`<h2>Demande enregistrée ✓</h2><p>Référence <b>${ref}</b>. Elle est maintenant visible dans les espaces Client et Loueur de cette démonstration.</p><p><a href="client.html">Voir mon espace client</a></p>`}
document.getElementById('closeModal').onclick=()=>modal.close();
document.getElementById('searchBtn').onclick=()=>{const city=document.getElementById('city').value;const found=cars.filter(c=>c.city===city);render(found.length?found:cars);document.getElementById('cars').scrollIntoView({behavior:'smooth'})};
function ai(){const q=document.getElementById('aiInput').value||'Marrakech, 5 jours, famille de 4, budget 2500 DH';const budget=(q.match(/(\d[\d\s]{2,})\s*(dh|mad)/i)||[])[1];const days=(q.match(/(\d+)\s*jours?/i)||[])[1]||5;let options=cars.filter(c=>!budget||c.price*Number(days)<=Number(budget.replace(/\s/g,''))).sort((a,b)=>a.price-b.price).slice(0,3);document.getElementById('aiAnswer').innerHTML=`<div class="bubble bot"><b>Analyse :</b> pour « ${q} », je privilégie ${options.map(x=>x.name+' ('+x.price+' DH/j)').join(', ')||'les offres les plus proches de votre budget'}. Les résultats sponsorisés restent identifiés séparément.</div>`}
document.getElementById('sendAi').onclick=ai;document.getElementById('askAi').onclick=()=>document.getElementById('ai').scrollIntoView({behavior:'smooth'});
['agencyBtn','joinBtn'].forEach(id=>document.getElementById(id).onclick=()=>{content.innerHTML='<h2>Espace loueur</h2><p>Gérez parc, tarifs, disponibilité, caution, assurance, kilométrage, livraison, promotions et réservations.</p><p><a href="loueur.html"><button class="primary">Ouvrir la démonstration loueur</button></a></p>';modal.showModal()});
document.getElementById('loginBtn').onclick=()=>{content.innerHTML='<h2>Choisir un espace</h2><p>La prochaine couche ajoutera l’authentification réelle. Pour cette V1, vous pouvez tester directement les trois rôles.</p><p><a href="client.html"><button class="primary">Client</button></a> <a href="loueur.html"><button class="primary">Loueur</button></a> <a href="admin.html"><button class="ghost">Admin</button></a></p>';modal.showModal()};
document.getElementById('compareBtn').onclick=()=>{content.innerHTML='<h2>Comparateur</h2>'+cars.slice(0,4).map(c=>`<p><b>${c.name}</b> — ${c.price} DH/j — caution ${c.deposit} — ${c.km}</p>`).join('');modal.showModal()};