let cars=[{name:'Dacia Logan',city:'Marrakech',price:320,gear:'Manuelle',deposit:'2 000 DH',km:'Illimité',icon:'🚙',sponsored:false},{name:'Renault Clio 5',city:'Casablanca',price:390,gear:'Automatique',deposit:'3 000 DH',km:'200 km/j',icon:'🚗',sponsored:true},{name:'Dacia Duster',city:'Agadir',price:520,gear:'Automatique',deposit:'3 500 DH',km:'Illimité',icon:'🚘',sponsored:false},{name:'Peugeot 208',city:'Rabat',price:410,gear:'Automatique',deposit:'2 500 DH',km:'250 km/j',icon:'🚗',sponsored:false},{name:'Hyundai Tucson',city:'Tanger',price:650,gear:'Automatique',deposit:'4 000 DH',km:'Illimité',icon:'🚙',sponsored:false},{name:'Fiat 500',city:'Fès',price:350,gear:'Manuelle',deposit:'2 000 DH',km:'200 km/j',icon:'🚗',sponsored:false}];
const grid=document.getElementById('carGrid'),modal=document.getElementById('modal'),content=document.getElementById('modalContent');
function render(list=cars){grid.innerHTML=list.map((c,i)=>`<article class="car"><div class="car-top">${c.sponsored?'<span class="badge">Sponsorisé</span>':''}${c.image_url?`<img src="${c.image_url}" alt="${c.name}" style="width:100%;height:100%;object-fit:cover">`:c.icon||'🚗'}</div><div class="car-body"><h3>${c.name}</h3><div class="meta">📍 ${c.city}${c.agency_name?' · '+c.agency_name:''}</div><div class="features"><span>${c.gear}</span><span>🛡 Assurance</span><span>${c.km}</span><span>Caution ${c.deposit}</span></div><div class="price-row"><div class="price"><b>${c.price} DH</b><small> / jour</small></div><button class="primary" onclick="reserve(${i})">Réserver</button></div></div></article>`).join('')}
render();
async function refreshRealCars(city=''){try{const rows=await loadVehicles(city);if(rows.length){cars=rows.map(v=>({id:v.id,agency_id:v.agency_id,name:`${v.brand} ${v.model}`,city:v.city,price:Number(v.price_per_day),gear:v.transmission||'—',deposit:`${Number(v.deposit||0)} DH`,km:v.mileage_policy||'—',sponsored:v.sponsored,image_url:v.image_url,agency_name:v.agencies?.name}));render()}}catch(e){console.warn(e)}}
refreshRealCars();
function reserve(i){const c=cars[i];content.innerHTML=`<h2>Demande de réservation</h2><p><b>${c.name}</b> — ${c.city} — ${c.price} DH/jour</p><label>Du<input type="date" id="bookFrom" value="${document.getElementById('from').value}"></label><br><label>Au<input type="date" id="bookTo" value="${document.getElementById('to').value}"></label><br><label>Message<input id="bookMsg" placeholder="Aéroport, siège bébé, etc."></label><br><br><button class="primary" onclick="submitBooking(${i})">Envoyer la demande</button>`;modal.showModal()}
async function submitBooking(i){const c=cars[i],from=document.getElementById('bookFrom').value,to=document.getElementById('bookTo').value,msg=document.getElementById('bookMsg').value;if(!from||!to){alert('Choisissez les dates.');return}if(!c.id){content.innerHTML='<h2>Véhicule de démonstration</h2><p>Les réservations réelles seront disponibles sur les véhicules ajoutés par les agences inscrites.</p>';return}try{await createBooking(c,from,to,msg);content.innerHTML='<h2>Demande envoyée ✓</h2><p>Votre réservation est enregistrée. Le loueur pourra la confirmer ou la refuser.</p>'}catch(e){if(e.message==='AUTH_REQUIRED')showAuth('client');else alert(e.message)}}
document.getElementById('closeModal').onclick=()=>modal.close();
document.getElementById('searchBtn').onclick=async()=>{const city=document.getElementById('city').value;try{const rows=await loadVehicles(city);if(rows.length){cars=rows.map(v=>({id:v.id,agency_id:v.agency_id,name:`${v.brand} ${v.model}`,city:v.city,price:Number(v.price_per_day),gear:v.transmission||'—',deposit:`${Number(v.deposit||0)} DH`,km:v.mileage_policy||'—',sponsored:v.sponsored,image_url:v.image_url,agency_name:v.agencies?.name}));render()}else render(cars.filter(c=>c.city===city))}catch(e){render(cars.filter(c=>c.city===city))}document.getElementById('cars').scrollIntoView({behavior:'smooth'})};
function ai(){const q=document.getElementById('aiInput').value||'Marrakech, 5 jours, famille de 4, budget 2500 DH';const budget=(q.match(/(\d[\d\s]{2,})\s*(dh|mad)/i)||[])[1];const days=(q.match(/(\d+)\s*jours?/i)||[])[1]||5;let options=cars.filter(c=>!budget||c.price*Number(days)<=Number(budget.replace(/\s/g,''))).sort((a,b)=>a.price-b.price).slice(0,3);document.getElementById('aiAnswer').innerHTML=`<div class="bubble bot"><b>Analyse :</b> pour « ${q} », je privilégie ${options.map(x=>x.name+' ('+x.price+' DH/j)').join(', ')||'les offres les plus proches de votre budget'}.</div>`}
document.getElementById('sendAi').onclick=ai;document.getElementById('askAi').onclick=()=>document.getElementById('ai').scrollIntoView({behavior:'smooth'});
function showAuth(role='client'){content.innerHTML=`<h2>${role==='loueur'?'Créer un compte loueur':'Connexion / inscription'}</h2><label>Nom complet<input id="authName" placeholder="Nom complet"></label><br><label>Email<input id="authEmail" type="email" placeholder="vous@email.com"></label><br><label>Mot de passe<input id="authPass" type="password" placeholder="8 caractères minimum"></label><br><br><button class="primary" onclick="doSignup('${role}')">Créer mon compte</button> <button class="ghost" onclick="doLogin()">Me connecter</button><div id="authMsg" class="meta" style="margin-top:14px"></div>`;modal.showModal()}
async function doSignup(role){try{const d=await signUpAutoRent({email:authEmail.value,password:authPass.value,full_name:authName.value,role});authMsg.textContent=d.session?'Compte créé et connecté.':'Compte créé. Vérifiez votre email si une confirmation est demandée.';if(d.session)setTimeout(()=>location.href=role==='loueur'?'loueur.html':'client.html',700)}catch(e){authMsg.textContent=e.message}}
async function doLogin(){try{await signInAutoRent(authEmail.value,authPass.value);const p=await getAutoRentProfile();location.href=p?.role==='loueur'?'loueur.html':'client.html'}catch(e){authMsg.textContent=e.message}}
document.getElementById('loginBtn').onclick=()=>showAuth('client');['agencyBtn','joinBtn'].forEach(id=>document.getElementById(id).onclick=()=>showAuth('loueur'));
document.getElementById('compareBtn').onclick=()=>{content.innerHTML='<h2>Comparateur</h2>'+cars.slice(0,4).map(c=>`<p><b>${c.name}</b> — ${c.price} DH/j — caution ${c.deposit} — ${c.km}</p>`).join('');modal.showModal()};